apiVersion: v1
kind: Service
metadata:
  name: {{ include "weinservice.fullname" . }}
  labels:
    {{- include "weinservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "weinservice.selectorLabels" . | nindent 4 }}

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name }}
  labels:
    release: {{ .Values.serviceMonitor.release }}
spec:
  selector:
    matchLabels:
      {{- include "weinservice.selectorLabels" . | nindent 6 }}
      #app: {{ include "weinservice.fullname" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
